server:
  port: 9522

spring:
  datasource:
    url: ${EMPLOYEE_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  ldap:
    urls: ${LDAP_URL}
    base: ${LDAP_BASE}
    username: ${LDAP_USERNAME}
    password: ${LDAP_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: DEBUG
